export const strings = {
    en: {
        start: "START",
        clueHistory: "Clue History",
        exit: "Exit",
        vote: "Vote",
        lobby: "Lobby",
        gameRules: "Game Rules",
        advancedSettings: "Advanced Settings",
        privacyMasking: "Privacy Masking",
        hardMode: "Hard Mode",
        pointMultiplier: "Point Multiplier",
        aiIntelligence: "AI Intelligence",
        doubleAgent: "Double Agent",
        visualTheme: "Theme",
        language: "Language",
        clueRounds: "Clue Rounds",
        discussionTimer: "Discussion Timer",
        fairPlay: "Fair Play Mode",
        localizedCategories: "Enable Localized Categories",
        saveChanges: "Save Changes",
        saved: "Settings Saved!",
        totalScore: "Total Score",
        playAgain: "Play Again",
        votingPhase: "Voting Phase",
        discuss: "Discuss! Who is the Imposter?",
        voteNow: "Vote Now",
        doubleDown: "Double Down",
        doubleDownSub: "(x2 Pts / -1 if wrong)",
        imposter: "Imposter",
        civilian: "Civilian",
        category: "CATEGORY",
        secretWord: "SECRET WORD",
        confidential: "CONFIDENTIAL",
        tapToReveal: "Tap to reveal your identity",
        holdToReveal: "Hold to reveal",
        unknown: "UNKNOWN",
        nextPlayer: "Next Player",
        analyzing: "Analyzing...",
        caught: "CAUGHT!",
        escaped: "ESCAPED!",
        imposterWin: "Imposter Wins!",
        civilianWin: "Civilians Win!",
        votingResult: "Voting Results",
        waitingFor: "Waiting for",
        passDevice: "Pass device to",
        aiGenerate: "AI Generate",
        aiGenerationFailed: "AI Generation failed",
        reroll: "Emergency Reroll",
        clueInputPlaceholder: "Type your clue...",
        clueError: "Keep it short (1-3 words max)",
        noClues: "No clues yet. Start the round!",
        aiIsThinking: "{name} is thinking...",
        whoIsImposter: "who is the Imposter?",
        aiIsChoosing: "AI {name} is choosing...",
        guessSecretWord: "Guess the Secret Word!",
        wasImposter: "was the Imposter!",
        imposterChance: "But they have one chance to escape...",
        theImposterWas: "THE IMPOSTER WAS",
        secretWordWas: "THE SECRET WORD WAS",
        cancel: "Cancel",
        generate: "Generate",
        disabled: "Disabled",
        fairPlaySub: "Imposter never starts first",
        privacyMaskingSub: "Blur word until held",
        pointMultiplierSub: "Enable Double Down betting",
        localizedCategoriesSub: "Japan-specific topics",
        doubleAgentSub: "2 Imposters mode",
        timerDuration: "Duration"
    },
    jp: {
        start: "スタート",
        clueHistory: "ヒント履歴",
        exit: "終了",
        vote: "投票",
        lobby: "ロビー",
        gameRules: "ゲームルール",
        advancedSettings: "詳細設定",
        privacyMasking: "プライバシー保護",
        hardMode: "ハードモード",
        pointMultiplier: "ポイント倍増 (賭け)",
        aiIntelligence: "AIの知能",
        doubleAgent: "ダブルエージェント",
        visualTheme: "テーマ",
        language: "言語",
        clueRounds: "ヒントのラウンド数",
        discussionTimer: "議論タイマー",
        fairPlay: "フェアプレイモード",
        localizedCategories: "日本限定トピック",
        saveChanges: "変更を保存",
        saved: "保存しました！",
        totalScore: "合計スコア",
        playAgain: "もう一度遊ぶ",
        votingPhase: "投票フェーズ",
        discuss: "インポスターは誰？議論しよう！",
        voteNow: "投票する",
        doubleDown: "ダブルダウン (賭け)",
        doubleDownSub: "(正解で2倍 / 不正解で-1点)",
        imposter: "インポスター",
        civilian: "市民",
        category: "カテゴリー",
        secretWord: "お題の言葉",
        confidential: "極秘",
        tapToReveal: "タップして正体を確認",
        holdToReveal: "長押しで確認",
        unknown: "不明",
        nextPlayer: "次のプレイヤーへ",
        analyzing: "分析中...",
        caught: "確保！",
        escaped: "逃走成功！",
        imposterWin: "インポスターの勝利！",
        civilianWin: "市民の勝利！",
        votingResult: "投票結果",
        waitingFor: "待機中",
        passDevice: "端末を渡してください",
        aiGenerate: "AI生成",
        aiGenerationFailed: "AI生成に失敗しました",
        reroll: "緊急リロール",
        clueInputPlaceholder: "ヒントを入力...",
        clueError: "短くしてください (1-3語)",
        noClues: "ヒントはまだありません",
        aiIsThinking: "{name} が考え中...",
        whoIsImposter: "インポスターは誰？",
        aiIsChoosing: "AI {name} が選択中...",
        guessSecretWord: "秘密の言葉を当てろ！",
        wasImposter: "がインポスターでした！",
        imposterChance: "しかし、逆転のチャンスがあります...",
        theImposterWas: "インポスターは...",
        secretWordWas: "秘密の言葉は...",
        cancel: "キャンセル",
        generate: "生成",
        disabled: "無効",
        fairPlaySub: "インポスターは最初に話さない",
        privacyMaskingSub: "長押しで言葉を表示",
        pointMultiplierSub: "ダブルダウン賭けを有効化",
        localizedCategoriesSub: "日本限定トピック",
        doubleAgentSub: "2人インポスターモード",
        timerDuration: "時間"
    }
};
